name: babel
channels:
  - bioconda
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7.*
  - numpy=1.17.*
  - pandas=0.25.*
  - matplotlib
  - anaconda::scipy=1.3.*
  - anaconda:scikit-learn=0.21.3
  - anaconda::statsmodels=0.10.*
  - pytorch::torchvision
  - pytorch::pytorch=1.3.1
  - anaconda::cudatoolkit=10.1.*
  - conda-forge::skorch=0.7.0
  - anaconda::tensorboard=2.0.0
  - conda-forge::jupyter
  - bioconda::anndata=0.6.22.*
  - bioconda::scanpy=1.4.*
  - conda-forge::intervaltree=3.0.*
  - conda-forge::leidenalg=0.7.0
  - anaconda::cached_property=1.5.*

